#!/bin/sh
# Run by Strap after installing Brewfile dependencies

cd $(dirname $0)/..

# Close terminal windows on successful exit code
/usr/libexec/PlistBuddy ~/Library/Preferences/com.apple.Terminal.plist -c \
  "Set 'Window Settings':Basic:shellExitAction 1"

# Setup my home directory how I like it
mkdir -pv ~/OSS ~/Development ~/Development/Projects/innerfuse
ln -vsf "$(brew --repository)" ~/OSS/Homebrew
ln -vsf "$(pwd -P)" ~/OSS/dotfiles

script/install-vscode-extensions
scrupt/setup-vscode-settings

# Use ZSH as my default Shell
if [ "$SHELL" != "/bin/zsh" ]; then
  chsh -s /bin/zsh wdeboer
fi

bin/touchid-enable-pam-sudo

# Ensure auto-update is always enabled
sudo defaults write /Library/Preferences/com.apple.commerce.plist AutoUpdate 1
